name: Main

on:
  push:
    branches:
      - live

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-south-1

    - name: Install Rename
      run: |
        apt-get update -y && apt-get install -y rename

    - name: Rename files and directories
      run: |
        find . -depth -exec rename 'y/A-Z/a-z/; s/\s+/_/g' {} +

    - name: Sync to S3 bucket
      run: |
        aws s3 sync ./ s3://projectdaimon/articles --delete --exclude ".git/*" --exclude ".github/*" --exclude "README.md" --exclude ".gitignore"
